name = "m1-async-worker"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[[d1_databases]]
binding = "DB"
database_name = "intellihire-db"
database_id = "63fdd68c-ff53-4aea-8327-2336b5e77587"

[[queues.consumers]]
queue = "m1-jobs-queue"
max_batch_size = 5
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "m1-jobs-dlq"
